# Generated by Django 5.0.3 on 2024-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlist',
            name='Category',
            field=models.CharField(max_length=500),
        ),
    ]
